### ISSUE TITLE
Replay an episode

### ISSUE THREAD

**Issue by davidvde72** [glorang/NUPlayer#2]
When you want to watch an episode again, it's almost impossible to restart it.
After starting, you have to push rewind within 0.5 seconds. Otherwise it just stops, because the watch bar is at the end.

Maybe, when starting an episode, and there are just 5-10 seconds remaining, start it from the beginning.

**Comment by glorang** [comment]
I've just pushed a commit that will restart the video from the beginning if progress is > 95%. This is inline with how the rest of the apps / resume points works.

Fix will probably be included in 1.2.0 release but not yet sure when I'll release it.

**Comment by davidvde72** [comment]
Fixed in 1.2.0
