### ISSUE TITLE
Feature request: use "channels" to show what's currently on

### ISSUE THREAD

**Issue by bmesuere** [glorang/NUPlayer#7]
Android TV apps can use [channels](https://developer.android.com/training/tv/discovery/recommendations-channel) to expose content on the home screen. Would it be possible to add the 3 live tv streams to the default NUPlayer channel? This would both serve as a shortcut the the respective stream and make it possible to show what's currently playing on those streams.

In addition, a small question about NUPlayer: is there a way to see the resolution and bitrate of the stream that's currently playing (e.g., using the developer options)? Does NUPlayer make use of the higher resolution streams that are mentioned in the changelog of the vrtNU app?

Thanks for creating this app! If you need any help testing stuff, I have a chromecast with google tv.

**Comment by glorang** [comment]
(Unfortunately) the short answer is "no".

The channels you refer to is something from Android TV, but Google TV != Android TV. Google only works with a select set of streaming providers that allows them to publish recommendations for Movies/TV shows (no Live TV) to the home screen.

https://developer.android.com/training/tv/start/google-tv
> Currently, Google is working with a limited number of providers at a time to integrate each provider into the feature.

This also requires you to publish your entire catalog to Google, this is definitely not something I can do.

What you probably want is something like this: https://tweakers.net/i/_cCHr-8DujYlxPSff0WHR_Y-dpI=/656x/filters:strip_icc():strip_exif()/i/2003960728.jpeg but this is not yet available in Europe for Google TV. When it becomes available it will still be doubtful if NUPlayer can implement it, guess the data will also pass via Google. Time will tell :-)

It could be implemented though for non Google TV users (bare Android TV users) but not sure if I want to spend much effort on this, I'll think about it.

NUPlayer is using adaptive streaming (DASH) which will automatically select highest available rate if your connection allows it, so yes, the app is using the (new) 1080p stream. You can clearly see it during the Euro2020 streams.

There is no developer overlay for this yet, but it seems possible and easy to do so you can expect this in a future release.

Testers are always welcome. Via Google Play you can join the Beta and provide feedback via Google Play or here, feedback is always welcome!

Thanks,

**Comment by MrBearPresident** [comment]
Hi 

I have a Mi-Box (so plain android TV) and first of all I want to thank you for making the app this has been such a delight during the euro2020 games. 
Me and my wife are really glad to not always go and search a phone to then cast the stream to the tv. The app makes it so much easier something VRT should have done in my opinion. So Thank you 

I would use the feature of having the livestreams available on the homescreen. 
So if you want to know if this feature is wanted or not. I want it.
It shouldn't be to complicated no live/updating images just the logo of the channel should be enough I guess.

**Comment by bmesuere** [comment]
Thanks for your reply. I also saw the page you linked about google tv but I do think Google TV uses the old channels as a fallback. Right now, the Telenet TV app is on my home screen with some tv channels and I doubt they are one of the early partners.

**Comment by glorang** [comment]
I've released 1.3.4 in the Beta Channel which includes two fixes : 

- When developer mode is enabled in NUPlayer settings you'll now get an "Info" icon in the video player that can toggle ExoPlayer's stream info. It includes video resolution, audio rate, codecs, playback state and some other less useful stuff (internal buffers).
- Via NUPlayer settings you can toggle the NUPlayer home screen channel

On Google TV it indeed falls back to the default channel. You can add/remove it as many times as you want, it will always reappear. Google TV does not support reordering of channels.

On Android TV it will appear automatically only the first time, once you remove and add it again it you have to manually select it again at the bottom of the home screen - this is as designed.

(For now?) channels only contain static logo image and no EPG data (as suggested by @MrBearPresident). It seems (too) difficult / not possible to update the screenshots and EPG data consistently when the app is running in the background or when it's not running at all.

Let me know if you have any comments or remarks!

**Comment by bmesuere** [comment]
This is great, thanks @glorang!

**Comment by glorang** [comment]
There was still a minor issue with cached logos but this is now fixed in (just) released 1.3.7.
