### ISSUE TITLE
Search and On Demand aren't working

### ISSUE THREAD

**Issue by Eejs** [glorang/NUPlayer#9]
I can log in and watch the live streams (via the home page or via the TV guide), but Search and On Demand aren't working.
- The search results remain empty, regardless of what I search for
- The On Demand sub pages are empty and result in the following:
   => Latest: Results in an error: "Could not get latest videos: 0 : null".
   => Series are empty.
   => Categories: the categories are displayed but when selecting one, the following error is displayed: "Could not get/set VRT.Nu category list: 0 : null" and then the section remains empty.
   => Catalog is empty.

I am running this on an NVidia ShieldTV Pro (2019). I don't know if there's a way to see more detailed logs that might be helpful to debug?

**Comment by glorang** [comment]
VRT asked me to take the app offline (see README in this repo as well) as they have released their own Android TV app. It's probably better and easier to install that one. 

The bug you've reported is fixed though but I do not provide any builds anymore. I really don't feel like getting in trouble with VRT. If you manage to build the project you should be able to sideload it, but then again, it's probably easier to use the official app.

Let me know if you want to give the building a try, I've purged all VRT brand images which will cause some trouble in the building process but guess I can replace them with some placeholders.

**Comment by Eejs** [comment]
Ah, sorry, I didn't check the README! I didn't know that VRT finally created their own AndroidTV app. I will check that one.
Thanks a lot for this app while waiting for VRT to create one. :-)
